sudo: false

language: node_js
arch:
  - amd64
  - ppc64le

node_js:
  - 'stable'
  - 12
  - 10

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm test
